### ISSUE TITLE
run

### ISSUE THREAD

**Issue by qmmp123** [BigMo/Zat-s-CSGO-Simple-internal-hack#1]
How to run it?

**Comment by BigMo** [comment]
You'll have to compile it first.
You can get the binaries (.dll) here: http://www.unknowncheats.me/forum/counterstrike-global-offensive/139216-zats-simple-internal-radar-and-glow.html
After you either downloaded the binaries or compiled it on your own, use your favourite injector to inject the hack into the game.

**Comment by qmmp123** [comment]
i've got vac ban. Cheat is Deteted on matchmaking

**Comment by BigMo** [comment]
Which injector did you use?

**Comment by qmmp123** [comment]
i used anonymous injector

**Comment by BigMo** [comment]
You did not use ANY other hacks within the last few months?

**Comment by qmmp123** [comment]
no i did'not
